// Plugin Version: 1.0.9.4, Dynamics 365 svcutil solid extension tool by Kipon ApS (c) 2019,2020,2021, Kjeld Poulsen
// This file is autogenerated. Do not touch the code manually.

using System;
using System.Linq;
using Kipon.Xrm.ServiceAPI;
using Microsoft.Xrm.Sdk;
namespace Kipon.Xrm
{
	public sealed class Version
	{
		public const string No = "1.0.9.4";
	}
}
namespace Kipon.Solid.Plugin.Entities
{
	public partial class SolidContextService : Kipon.Xrm.ServiceAPI.IEntityCache { }
	[Kipon.Xrm.Attributes.Export(typeof(IUnitOfWork))]
	[Kipon.Xrm.Attributes.Export(typeof(Kipon.Xrm.IUnitOfWork))]
	public sealed partial class CrmUnitOfWork: IUnitOfWork, IDisposable, Kipon.Xrm.IService
	{
		private SolidContextService context;
		private IOrganizationService _service;
		public CrmUnitOfWork(IOrganizationService orgService)
		{
			this._service = orgService;
			this.context = new SolidContextService(_service);
		}

        public void Dispose()
        {
            context.Dispose();
        }

        public R ExecuteRequest<R>(OrganizationRequest request) where R : OrganizationResponse
        {
            return (R)this.context.Execute(request);
        }

        public OrganizationResponse Execute(OrganizationRequest request)
        {
            return this.context.Execute(request);
        }


        public Guid Create(Entity entity)
        {
            return this._service.Create(entity);
        }

        public void Update(Entity entity)
        {
            this._service.Update(entity);
        }

        public void Delete(Entity entity)
        {
            this._service.Delete(entity.LogicalName, entity.Id);
        }

        public void ClearContext()
        {
            var candidates = this.context.GetAttachedEntities().ToArray();
            foreach (var can in candidates) 
            {
                context.Detach(can);
            }
        }

        public void Detach(string logicalName, params Guid[] ids)
        {
            if (this.context != null)
            {
                var candidates = (from c in this.context.GetAttachedEntities() where c.LogicalName == logicalName select c);
                if (ids != null && ids.Length > 0)
                {
                    candidates = (from c in candidates where ids.Contains(c.Id) select c);
                }
                foreach (var r in candidates.ToArray())
                {
                    context.Detach(r);
                }
            }
        }

        public void Detach(Microsoft.Xrm.Sdk.EntityReference eref)
        {
            this.Detach(eref.LogicalName, eref.Id);
        }

        public void Detach(Microsoft.Xrm.Sdk.Entity ent)
        {
            this.Detach(ent.LogicalName, ent.Id);
        }

        public Kipon.Xrm.ServiceAPI.IEntityCache Cache => this.context;

		void Kipon.Xrm.IService.OnStepFinalized()
		{
			foreach (var e in this.context.GetAttachedEntities().ToArray()) this.context.Detach(e);
		}

		private Kipon.Xrm.IRepository<Account> _accounts; 
		public Kipon.Xrm.IRepository<Account> Accounts
		{
			get
			{
				if (_accounts == null)
					{
						_accounts = new CrmRepository<Account>(this.context, this._service);
					}
				return _accounts;
			}
		}
		private Kipon.Xrm.IRepository<PhoneCall> _phonecalls; 
		public Kipon.Xrm.IRepository<PhoneCall> Phonecalls
		{
			get
			{
				if (_phonecalls == null)
					{
						_phonecalls = new CrmRepository<PhoneCall>(this.context, this._service);
					}
				return _phonecalls;
			}
		}
		private Kipon.Xrm.IRepository<Contact> _contacts; 
		public Kipon.Xrm.IRepository<Contact> Contacts
		{
			get
			{
				if (_contacts == null)
					{
						_contacts = new CrmRepository<Contact>(this.context, this._service);
					}
				return _contacts;
			}
		}
		private Kipon.Xrm.IRepository<Invoice> _invoices; 
		public Kipon.Xrm.IRepository<Invoice> Invoices
		{
			get
			{
				if (_invoices == null)
					{
						_invoices = new CrmRepository<Invoice>(this.context, this._service);
					}
				return _invoices;
			}
		}
		private Kipon.Xrm.IRepository<Lead> _leads; 
		public Kipon.Xrm.IRepository<Lead> Leads
		{
			get
			{
				if (_leads == null)
					{
						_leads = new CrmRepository<Lead>(this.context, this._service);
					}
				return _leads;
			}
		}
		private Kipon.Xrm.IRepository<Opportunity> _opportunities; 
		public Kipon.Xrm.IRepository<Opportunity> Opportunities
		{
			get
			{
				if (_opportunities == null)
					{
						_opportunities = new CrmRepository<Opportunity>(this.context, this._service);
					}
				return _opportunities;
			}
		}
		private Kipon.Xrm.IRepository<SalesOrder> _salesorders; 
		public Kipon.Xrm.IRepository<SalesOrder> Salesorders
		{
			get
			{
				if (_salesorders == null)
					{
						_salesorders = new CrmRepository<SalesOrder>(this.context, this._service);
					}
				return _salesorders;
			}
		}
		private Kipon.Xrm.IRepository<Quote> _quotes; 
		public Kipon.Xrm.IRepository<Quote> Quotes
		{
			get
			{
				if (_quotes == null)
					{
						_quotes = new CrmRepository<Quote>(this.context, this._service);
					}
				return _quotes;
			}
		}
		private Kipon.Xrm.IRepository<SystemUser> _systemusers; 
		public Kipon.Xrm.IRepository<SystemUser> Systemusers
		{
			get
			{
				if (_systemusers == null)
					{
						_systemusers = new CrmRepository<SystemUser>(this.context, this._service);
					}
				return _systemusers;
			}
		}
		private Kipon.Xrm.IRepository<kipon_datepoc> _datepocs; 
		public Kipon.Xrm.IRepository<kipon_datepoc> Datepocs
		{
			get
			{
				if (_datepocs == null)
					{
						_datepocs = new CrmRepository<kipon_datepoc>(this.context, this._service);
					}
				return _datepocs;
			}
		}
		private Kipon.Xrm.IRepository<kipon_multitest> _multitests; 
		public Kipon.Xrm.IRepository<kipon_multitest> Multitests
		{
			get
			{
				if (_multitests == null)
					{
						_multitests = new CrmRepository<kipon_multitest>(this.context, this._service);
					}
				return _multitests;
			}
		}
		private Kipon.Xrm.IRepository<Template> _templates; 
		public Kipon.Xrm.IRepository<Template> Templates
		{
			get
			{
				if (_templates == null)
					{
						_templates = new CrmRepository<Template>(this.context, this._service);
					}
				return _templates;
			}
		}
	}
	[Kipon.Xrm.Attributes.Export(typeof(IAdminUnitOfWork))]
	[Kipon.Xrm.Attributes.Export(typeof(Kipon.Xrm.IAdminUnitOfWork))]
	public sealed partial class AdminCrmUnitOfWork : IAdminUnitOfWork, IDisposable, Kipon.Xrm.IService
	{
		private SolidContextService context;
		private IOrganizationService _service;
		public AdminCrmUnitOfWork(IOrganizationService orgService)
		{
			this._service = orgService;
			this.context = new SolidContextService(_service);
		}

        public void Dispose()
        {
            context.Dispose();
        }

        public R ExecuteRequest<R>(OrganizationRequest request) where R : OrganizationResponse
        {
            return (R)this.context.Execute(request);
        }

        public OrganizationResponse Execute(OrganizationRequest request)
        {
            return this.context.Execute(request);
        }


        public Guid Create(Entity entity)
        {
            return this._service.Create(entity);
        }

        public void Update(Entity entity)
        {
            this._service.Update(entity);
        }

        public void Delete(Entity entity)
        {
            this._service.Delete(entity.LogicalName, entity.Id);
        }

        public void ClearContext()
        {
            var candidates = this.context.GetAttachedEntities().ToArray();
            foreach (var can in candidates) 
            {
                context.Detach(can);
            }
        }

        public void Detach(string logicalName, params Guid[] ids)
        {
            if (this.context != null)
            {
                var candidates = (from c in this.context.GetAttachedEntities() where c.LogicalName == logicalName select c);
                if (ids != null && ids.Length > 0)
                {
                    candidates = (from c in candidates where ids.Contains(c.Id) select c);
                }
                foreach (var r in candidates.ToArray())
                {
                    context.Detach(r);
                }
            }
        }

        public void Detach(Microsoft.Xrm.Sdk.EntityReference eref)
        {
            this.Detach(eref.LogicalName, eref.Id);
        }

        public void Detach(Microsoft.Xrm.Sdk.Entity ent)
        {
            this.Detach(ent.LogicalName, ent.Id);
        }

        public Kipon.Xrm.ServiceAPI.IEntityCache Cache => this.context;

		void Kipon.Xrm.IService.OnStepFinalized()
		{
			foreach (var e in this.context.GetAttachedEntities().ToArray()) this.context.Detach(e);
		}

		private Kipon.Xrm.IRepository<Account> _accounts; 
		public Kipon.Xrm.IRepository<Account> Accounts
		{
			get
			{
				if (_accounts == null)
					{
						_accounts = new CrmRepository<Account>(this.context, this._service);
					}
				return _accounts;
			}
		}
		private Kipon.Xrm.IRepository<PhoneCall> _phonecalls; 
		public Kipon.Xrm.IRepository<PhoneCall> Phonecalls
		{
			get
			{
				if (_phonecalls == null)
					{
						_phonecalls = new CrmRepository<PhoneCall>(this.context, this._service);
					}
				return _phonecalls;
			}
		}
		private Kipon.Xrm.IRepository<Contact> _contacts; 
		public Kipon.Xrm.IRepository<Contact> Contacts
		{
			get
			{
				if (_contacts == null)
					{
						_contacts = new CrmRepository<Contact>(this.context, this._service);
					}
				return _contacts;
			}
		}
		private Kipon.Xrm.IRepository<Invoice> _invoices; 
		public Kipon.Xrm.IRepository<Invoice> Invoices
		{
			get
			{
				if (_invoices == null)
					{
						_invoices = new CrmRepository<Invoice>(this.context, this._service);
					}
				return _invoices;
			}
		}
		private Kipon.Xrm.IRepository<Lead> _leads; 
		public Kipon.Xrm.IRepository<Lead> Leads
		{
			get
			{
				if (_leads == null)
					{
						_leads = new CrmRepository<Lead>(this.context, this._service);
					}
				return _leads;
			}
		}
		private Kipon.Xrm.IRepository<Opportunity> _opportunities; 
		public Kipon.Xrm.IRepository<Opportunity> Opportunities
		{
			get
			{
				if (_opportunities == null)
					{
						_opportunities = new CrmRepository<Opportunity>(this.context, this._service);
					}
				return _opportunities;
			}
		}
		private Kipon.Xrm.IRepository<SalesOrder> _salesorders; 
		public Kipon.Xrm.IRepository<SalesOrder> Salesorders
		{
			get
			{
				if (_salesorders == null)
					{
						_salesorders = new CrmRepository<SalesOrder>(this.context, this._service);
					}
				return _salesorders;
			}
		}
		private Kipon.Xrm.IRepository<Quote> _quotes; 
		public Kipon.Xrm.IRepository<Quote> Quotes
		{
			get
			{
				if (_quotes == null)
					{
						_quotes = new CrmRepository<Quote>(this.context, this._service);
					}
				return _quotes;
			}
		}
		private Kipon.Xrm.IRepository<SystemUser> _systemusers; 
		public Kipon.Xrm.IRepository<SystemUser> Systemusers
		{
			get
			{
				if (_systemusers == null)
					{
						_systemusers = new CrmRepository<SystemUser>(this.context, this._service);
					}
				return _systemusers;
			}
		}
		private Kipon.Xrm.IRepository<kipon_datepoc> _datepocs; 
		public Kipon.Xrm.IRepository<kipon_datepoc> Datepocs
		{
			get
			{
				if (_datepocs == null)
					{
						_datepocs = new CrmRepository<kipon_datepoc>(this.context, this._service);
					}
				return _datepocs;
			}
		}
		private Kipon.Xrm.IRepository<kipon_multitest> _multitests; 
		public Kipon.Xrm.IRepository<kipon_multitest> Multitests
		{
			get
			{
				if (_multitests == null)
					{
						_multitests = new CrmRepository<kipon_multitest>(this.context, this._service);
					}
				return _multitests;
			}
		}
		private Kipon.Xrm.IRepository<Template> _templates; 
		public Kipon.Xrm.IRepository<Template> Templates
		{
			get
			{
				if (_templates == null)
					{
						_templates = new CrmRepository<Template>(this.context, this._service);
					}
				return _templates;
			}
		}
	}
	public partial interface IAccountTarget : Kipon.Xrm.Target<Account>{ }
	public partial interface IAccountPreimage : Kipon.Xrm.Preimage<Account>{ }
	public partial interface IAccountPostimage : Kipon.Xrm.Postimage<Account>{ }
	public partial interface IAccountMergedimage : Kipon.Xrm.Mergedimage<Account>{ }
	public sealed partial class Account :
		IAccountTarget,
		IAccountPreimage,
		IAccountPostimage,
		IAccountMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface IPhoneCallTarget : Kipon.Xrm.Target<PhoneCall>{ }
	public partial interface IPhoneCallPreimage : Kipon.Xrm.Preimage<PhoneCall>{ }
	public partial interface IPhoneCallPostimage : Kipon.Xrm.Postimage<PhoneCall>{ }
	public partial interface IPhoneCallMergedimage : Kipon.Xrm.Mergedimage<PhoneCall>{ }
	public sealed partial class PhoneCall :
		IPhoneCallTarget,
		IPhoneCallPreimage,
		IPhoneCallPostimage,
		IPhoneCallMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface IContactTarget : Kipon.Xrm.Target<Contact>{ }
	public partial interface IContactPreimage : Kipon.Xrm.Preimage<Contact>{ }
	public partial interface IContactPostimage : Kipon.Xrm.Postimage<Contact>{ }
	public partial interface IContactMergedimage : Kipon.Xrm.Mergedimage<Contact>{ }
	public sealed partial class Contact :
		IContactTarget,
		IContactPreimage,
		IContactPostimage,
		IContactMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface IInvoiceTarget : Kipon.Xrm.Target<Invoice>{ }
	public partial interface IInvoicePreimage : Kipon.Xrm.Preimage<Invoice>{ }
	public partial interface IInvoicePostimage : Kipon.Xrm.Postimage<Invoice>{ }
	public partial interface IInvoiceMergedimage : Kipon.Xrm.Mergedimage<Invoice>{ }
	public sealed partial class Invoice :
		IInvoiceTarget,
		IInvoicePreimage,
		IInvoicePostimage,
		IInvoiceMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface ILeadTarget : Kipon.Xrm.Target<Lead>{ }
	public partial interface ILeadPreimage : Kipon.Xrm.Preimage<Lead>{ }
	public partial interface ILeadPostimage : Kipon.Xrm.Postimage<Lead>{ }
	public partial interface ILeadMergedimage : Kipon.Xrm.Mergedimage<Lead>{ }
	public sealed partial class Lead :
		ILeadTarget,
		ILeadPreimage,
		ILeadPostimage,
		ILeadMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface IOpportunityTarget : Kipon.Xrm.Target<Opportunity>{ }
	public partial interface IOpportunityPreimage : Kipon.Xrm.Preimage<Opportunity>{ }
	public partial interface IOpportunityPostimage : Kipon.Xrm.Postimage<Opportunity>{ }
	public partial interface IOpportunityMergedimage : Kipon.Xrm.Mergedimage<Opportunity>{ }
	public sealed partial class Opportunity :
		IOpportunityTarget,
		IOpportunityPreimage,
		IOpportunityPostimage,
		IOpportunityMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface ISalesOrderTarget : Kipon.Xrm.Target<SalesOrder>{ }
	public partial interface ISalesOrderPreimage : Kipon.Xrm.Preimage<SalesOrder>{ }
	public partial interface ISalesOrderPostimage : Kipon.Xrm.Postimage<SalesOrder>{ }
	public partial interface ISalesOrderMergedimage : Kipon.Xrm.Mergedimage<SalesOrder>{ }
	public sealed partial class SalesOrder :
		ISalesOrderTarget,
		ISalesOrderPreimage,
		ISalesOrderPostimage,
		ISalesOrderMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface IQuoteTarget : Kipon.Xrm.Target<Quote>{ }
	public partial interface IQuotePreimage : Kipon.Xrm.Preimage<Quote>{ }
	public partial interface IQuotePostimage : Kipon.Xrm.Postimage<Quote>{ }
	public partial interface IQuoteMergedimage : Kipon.Xrm.Mergedimage<Quote>{ }
	public sealed partial class Quote :
		IQuoteTarget,
		IQuotePreimage,
		IQuotePostimage,
		IQuoteMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface ISystemUserTarget : Kipon.Xrm.Target<SystemUser>{ }
	public partial interface ISystemUserPreimage : Kipon.Xrm.Preimage<SystemUser>{ }
	public partial interface ISystemUserPostimage : Kipon.Xrm.Postimage<SystemUser>{ }
	public partial interface ISystemUserMergedimage : Kipon.Xrm.Mergedimage<SystemUser>{ }
	public sealed partial class SystemUser :
		ISystemUserTarget,
		ISystemUserPreimage,
		ISystemUserPostimage,
		ISystemUserMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface Ikipon_datepocTarget : Kipon.Xrm.Target<kipon_datepoc>{ }
	public partial interface Ikipon_datepocPreimage : Kipon.Xrm.Preimage<kipon_datepoc>{ }
	public partial interface Ikipon_datepocPostimage : Kipon.Xrm.Postimage<kipon_datepoc>{ }
	public partial interface Ikipon_datepocMergedimage : Kipon.Xrm.Mergedimage<kipon_datepoc>{ }
	public sealed partial class kipon_datepoc :
		Ikipon_datepocTarget,
		Ikipon_datepocPreimage,
		Ikipon_datepocPostimage,
		Ikipon_datepocMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface Ikipon_multitestTarget : Kipon.Xrm.Target<kipon_multitest>{ }
	public partial interface Ikipon_multitestPreimage : Kipon.Xrm.Preimage<kipon_multitest>{ }
	public partial interface Ikipon_multitestPostimage : Kipon.Xrm.Postimage<kipon_multitest>{ }
	public partial interface Ikipon_multitestMergedimage : Kipon.Xrm.Mergedimage<kipon_multitest>{ }
	public sealed partial class kipon_multitest :
		Ikipon_multitestTarget,
		Ikipon_multitestPreimage,
		Ikipon_multitestPostimage,
		Ikipon_multitestMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public partial interface ITemplateTarget : Kipon.Xrm.Target<Template>{ }
	public partial interface ITemplatePreimage : Kipon.Xrm.Preimage<Template>{ }
	public partial interface ITemplatePostimage : Kipon.Xrm.Postimage<Template>{ }
	public partial interface ITemplateMergedimage : Kipon.Xrm.Mergedimage<Template>{ }
	public sealed partial class Template :
		ITemplateTarget,
		ITemplatePreimage,
		ITemplatePostimage,
		ITemplateMergedimage
	{
		public Microsoft.Xrm.Sdk.AttributeCollection TargetAttributes { get; set; }
		public Microsoft.Xrm.Sdk.AttributeCollection PreimageAttributes { get; set; }
	}
	public sealed class AccountReference : Kipon.Xrm.TargetReference<Account>
	{
		public AccountReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => Account.EntityLogicalName;
	}
	public sealed class PhoneCallReference : Kipon.Xrm.TargetReference<PhoneCall>
	{
		public PhoneCallReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => PhoneCall.EntityLogicalName;
	}
	public sealed class ContactReference : Kipon.Xrm.TargetReference<Contact>
	{
		public ContactReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => Contact.EntityLogicalName;
	}
	public sealed class InvoiceReference : Kipon.Xrm.TargetReference<Invoice>
	{
		public InvoiceReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => Invoice.EntityLogicalName;
	}
	public sealed class LeadReference : Kipon.Xrm.TargetReference<Lead>
	{
		public LeadReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => Lead.EntityLogicalName;
	}
	public sealed class OpportunityReference : Kipon.Xrm.TargetReference<Opportunity>
	{
		public OpportunityReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => Opportunity.EntityLogicalName;
	}
	public sealed class SalesOrderReference : Kipon.Xrm.TargetReference<SalesOrder>
	{
		public SalesOrderReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => SalesOrder.EntityLogicalName;
	}
	public sealed class QuoteReference : Kipon.Xrm.TargetReference<Quote>
	{
		public QuoteReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => Quote.EntityLogicalName;
	}
	public sealed class SystemUserReference : Kipon.Xrm.TargetReference<SystemUser>
	{
		public SystemUserReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => SystemUser.EntityLogicalName;
	}
	public sealed class kipon_datepocReference : Kipon.Xrm.TargetReference<kipon_datepoc>
	{
		public kipon_datepocReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => kipon_datepoc.EntityLogicalName;
	}
	public sealed class kipon_multitestReference : Kipon.Xrm.TargetReference<kipon_multitest>
	{
		public kipon_multitestReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => kipon_multitest.EntityLogicalName;
	}
	public sealed class TemplateReference : Kipon.Xrm.TargetReference<Template>
	{
		public TemplateReference(EntityReference target): base(target){ }
		protected sealed override string _logicalName => Template.EntityLogicalName;
	}
	public partial interface IUnitOfWork : Kipon.Xrm.IUnitOfWork
	{
		#region entity repositories
		Kipon.Xrm.IRepository<Account> Accounts { get; }
		Kipon.Xrm.IRepository<PhoneCall> Phonecalls { get; }
		Kipon.Xrm.IRepository<Contact> Contacts { get; }
		Kipon.Xrm.IRepository<Invoice> Invoices { get; }
		Kipon.Xrm.IRepository<Lead> Leads { get; }
		Kipon.Xrm.IRepository<Opportunity> Opportunities { get; }
		Kipon.Xrm.IRepository<SalesOrder> Salesorders { get; }
		Kipon.Xrm.IRepository<Quote> Quotes { get; }
		Kipon.Xrm.IRepository<SystemUser> Systemusers { get; }
		Kipon.Xrm.IRepository<kipon_datepoc> Datepocs { get; }
		Kipon.Xrm.IRepository<kipon_multitest> Multitests { get; }
		Kipon.Xrm.IRepository<Template> Templates { get; }
		#endregion
	}
	public partial interface IAdminUnitOfWork : Kipon.Xrm.IAdminUnitOfWork, IUnitOfWork { }
   public class CrmRepository<T> : Kipon.Xrm.IRepository<T> where T: Microsoft.Xrm.Sdk.Entity, new() 
    {
        private SolidContextService context;
        private Microsoft.Xrm.Sdk.IOrganizationService _service;

        public CrmRepository(SolidContextService context, Microsoft.Xrm.Sdk.IOrganizationService service)
        {
            this.context = context;
            this._service = service;
        }

        public IQueryable<T> GetQuery()
        {
            var q = context.CreateQuery<T>();
            return new Kipon.Xrm.Implementations.NoCacheQueryable<T>(q, this.context);
        }

        public void Delete(T entity)
        {
            this._service.Delete(entity.LogicalName, entity.Id);
        }

        public void Add(T entity)
        {
            this._service.Create(entity);
        }

        public void Update(T entity)
        {
            this._service.Update(entity);
        }

        public T GetById(Guid id)
        {
            return (from q in this.GetQuery()
                    where q.Id == id
                    select q).Single();
        }

        public void Attach(T entity)
        {
            this.context.Attach(entity);
        }

        public void Detach(T entity)
        {
            this.context.Detach(entity);
        }
    }
	public enum BudgetEnum
	{
		NoCommittedBudget = 0,
		MAyBuy = 1,
		CanBuy = 2,
		WillBuy = 3
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum AccountState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	public partial class Account
	{
		public enum PreferredContactMethodCodeEnum
		{
			Any = 1,
			Email = 2,
			Phone = 3,
			Fax = 4,
			Mail = 5,
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredcontactmethodcode")]
		public PreferredContactMethodCodeEnum? PreferredContactMethodCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredcontactmethodcode");
				if (optionSet != null)
				{
					return (PreferredContactMethodCodeEnum)optionSet.Value;
				}
				return null;
			}
			set
			{
				this.OnPropertyChanging("PreferredContactMethodCode");
				if (value != null)
				{
					this.SetAttributeValue("preferredcontactmethodcode", new Microsoft.Xrm.Sdk.OptionSetValue((int)value.Value));
					this.OnPropertyChanged("PreferredContactMethodCode");
					return;
				}
				this.SetAttributeValue("preferredcontactmethodcode", null);
				this.OnPropertyChanged("PreferredContactMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("new_multiselectbudget")]
		public BudgetEnum[] MultiSelectBudget
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValueCollection optionSetValues = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValueCollection>("new_multiselectbudget");
				if (optionSetValues != null && optionSetValues.Count > 0)
				{
					return (from v in optionSetValues select (BudgetEnum)v.Value).ToArray();
				}
				return null;
			}
			set
			{
				this.OnPropertyChanging("new_multiselectbudget");
				if (value != null && value.Length > 0)
				{
					var result = new Microsoft.Xrm.Sdk.OptionSetValueCollection();
					foreach (var v in value) result.Add(new Microsoft.Xrm.Sdk.OptionSetValue((int)v));
					this.SetAttributeValue("new_multiselectbudget", result);
					this.OnPropertyChanged("new_multiselectbudget");
					return;
				}
				this.SetAttributeValue("new_multiselectbudget", null);
				this.OnPropertyChanged("new_multiselectbudget");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("accountcategorycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue AccountCategoryCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("accountcategorycode");
			set
			{
				this.OnPropertyChanging("AccountCategoryCode");
					this.SetAttributeValue("accountcategorycode", value);
				this.OnPropertyChanged("AccountCategoryCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("accountclassificationcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue AccountClassificationCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("accountclassificationcode");
			set
			{
				this.OnPropertyChanging("AccountClassificationCode");
					this.SetAttributeValue("accountclassificationcode", value);
				this.OnPropertyChanged("AccountClassificationCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("accountratingcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue AccountRatingCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("accountratingcode");
			set
			{
				this.OnPropertyChanging("AccountRatingCode");
					this.SetAttributeValue("accountratingcode", value);
				this.OnPropertyChanged("AccountRatingCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address1_AddressTypeCode");
					this.SetAttributeValue("address1_addresstypecode", value);
				this.OnPropertyChanged("Address1_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_freighttermscode");
			set
			{
				this.OnPropertyChanging("Address1_FreightTermsCode");
					this.SetAttributeValue("address1_freighttermscode", value);
				this.OnPropertyChanged("Address1_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address1_ShippingMethodCode");
					this.SetAttributeValue("address1_shippingmethodcode", value);
				this.OnPropertyChanged("Address1_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address2_AddressTypeCode");
					this.SetAttributeValue("address2_addresstypecode", value);
				this.OnPropertyChanged("Address2_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_freighttermscode");
			set
			{
				this.OnPropertyChanging("Address2_FreightTermsCode");
					this.SetAttributeValue("address2_freighttermscode", value);
				this.OnPropertyChanged("Address2_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address2_ShippingMethodCode");
					this.SetAttributeValue("address2_shippingmethodcode", value);
				this.OnPropertyChanged("Address2_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("businesstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue BusinessTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("businesstypecode");
			set
			{
				this.OnPropertyChanging("BusinessTypeCode");
					this.SetAttributeValue("businesstypecode", value);
				this.OnPropertyChanged("BusinessTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("customersizecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue CustomerSizeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("customersizecode");
			set
			{
				this.OnPropertyChanging("CustomerSizeCode");
					this.SetAttributeValue("customersizecode", value);
				this.OnPropertyChanged("CustomerSizeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("customertypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue CustomerTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("customertypecode");
			set
			{
				this.OnPropertyChanging("CustomerTypeCode");
					this.SetAttributeValue("customertypecode", value);
				this.OnPropertyChanged("CustomerTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("industrycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue IndustryCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("industrycode");
			set
			{
				this.OnPropertyChanging("IndustryCode");
					this.SetAttributeValue("industrycode", value);
				this.OnPropertyChanged("IndustryCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("ownershipcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue OwnershipCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("ownershipcode");
			set
			{
				this.OnPropertyChanging("OwnershipCode");
					this.SetAttributeValue("ownershipcode", value);
				this.OnPropertyChanged("OwnershipCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("paymenttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PaymentTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("paymenttermscode");
			set
			{
				this.OnPropertyChanging("PaymentTermsCode");
					this.SetAttributeValue("paymenttermscode", value);
				this.OnPropertyChanged("PaymentTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredappointmentdaycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredAppointmentDayCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredappointmentdaycode");
			set
			{
				this.OnPropertyChanging("PreferredAppointmentDayCode");
					this.SetAttributeValue("preferredappointmentdaycode", value);
				this.OnPropertyChanged("PreferredAppointmentDayCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredappointmenttimecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredAppointmentTimeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredappointmenttimecode");
			set
			{
				this.OnPropertyChanging("PreferredAppointmentTimeCode");
					this.SetAttributeValue("preferredappointmenttimecode", value);
				this.OnPropertyChanged("PreferredAppointmentTimeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shippingmethodcode");
			set
			{
				this.OnPropertyChanging("ShippingMethodCode");
					this.SetAttributeValue("shippingmethodcode", value);
				this.OnPropertyChanged("ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("territorycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue TerritoryCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("territorycode");
			set
			{
				this.OnPropertyChanging("TerritoryCode");
					this.SetAttributeValue("territorycode", value);
				this.OnPropertyChanged("TerritoryCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public AccountState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((AccountState)(System.Enum.ToObject(typeof(AccountState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum PhoneCallState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 2,
	}
	public partial class PhoneCall
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("prioritycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PriorityCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
			set
			{
				this.OnPropertyChanging("PriorityCode");
					this.SetAttributeValue("prioritycode", value);
				this.OnPropertyChanged("PriorityCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public PhoneCallState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((PhoneCallState)(System.Enum.ToObject(typeof(PhoneCallState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum ContactState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	public partial class Contact
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("accountrolecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue AccountRoleCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("accountrolecode");
			set
			{
				this.OnPropertyChanging("AccountRoleCode");
					this.SetAttributeValue("accountrolecode", value);
				this.OnPropertyChanged("AccountRoleCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address1_AddressTypeCode");
					this.SetAttributeValue("address1_addresstypecode", value);
				this.OnPropertyChanged("Address1_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_freighttermscode");
			set
			{
				this.OnPropertyChanging("Address1_FreightTermsCode");
					this.SetAttributeValue("address1_freighttermscode", value);
				this.OnPropertyChanged("Address1_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address1_ShippingMethodCode");
					this.SetAttributeValue("address1_shippingmethodcode", value);
				this.OnPropertyChanged("Address1_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address2_AddressTypeCode");
					this.SetAttributeValue("address2_addresstypecode", value);
				this.OnPropertyChanged("Address2_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_freighttermscode");
			set
			{
				this.OnPropertyChanging("Address2_FreightTermsCode");
					this.SetAttributeValue("address2_freighttermscode", value);
				this.OnPropertyChanged("Address2_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address2_ShippingMethodCode");
					this.SetAttributeValue("address2_shippingmethodcode", value);
				this.OnPropertyChanged("Address2_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address3_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address3_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address3_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address3_AddressTypeCode");
					this.SetAttributeValue("address3_addresstypecode", value);
				this.OnPropertyChanged("Address3_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address3_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address3_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address3_freighttermscode");
			set
			{
				this.OnPropertyChanging("Address3_FreightTermsCode");
					this.SetAttributeValue("address3_freighttermscode", value);
				this.OnPropertyChanged("Address3_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address3_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address3_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address3_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address3_ShippingMethodCode");
					this.SetAttributeValue("address3_shippingmethodcode", value);
				this.OnPropertyChanged("Address3_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("customersizecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue CustomerSizeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("customersizecode");
			set
			{
				this.OnPropertyChanging("CustomerSizeCode");
					this.SetAttributeValue("customersizecode", value);
				this.OnPropertyChanged("CustomerSizeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("customertypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue CustomerTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("customertypecode");
			set
			{
				this.OnPropertyChanging("CustomerTypeCode");
					this.SetAttributeValue("customertypecode", value);
				this.OnPropertyChanged("CustomerTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("educationcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue EducationCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("educationcode");
			set
			{
				this.OnPropertyChanging("EducationCode");
					this.SetAttributeValue("educationcode", value);
				this.OnPropertyChanged("EducationCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("familystatuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue FamilyStatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("familystatuscode");
			set
			{
				this.OnPropertyChanging("FamilyStatusCode");
					this.SetAttributeValue("familystatuscode", value);
				this.OnPropertyChanged("FamilyStatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("gendercode")]
		public Microsoft.Xrm.Sdk.OptionSetValue GenderCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("gendercode");
			set
			{
				this.OnPropertyChanging("GenderCode");
					this.SetAttributeValue("gendercode", value);
				this.OnPropertyChanged("GenderCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("haschildrencode")]
		public Microsoft.Xrm.Sdk.OptionSetValue HasChildrenCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("haschildrencode");
			set
			{
				this.OnPropertyChanging("HasChildrenCode");
					this.SetAttributeValue("haschildrencode", value);
				this.OnPropertyChanged("HasChildrenCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("leadsourcecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue LeadSourceCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("leadsourcecode");
			set
			{
				this.OnPropertyChanging("LeadSourceCode");
					this.SetAttributeValue("leadsourcecode", value);
				this.OnPropertyChanged("LeadSourceCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("msdyn_orgchangestatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue msdyn_orgchangestatus
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msdyn_orgchangestatus");
			set
			{
				this.OnPropertyChanging("msdyn_orgchangestatus");
					this.SetAttributeValue("msdyn_orgchangestatus", value);
				this.OnPropertyChanged("msdyn_orgchangestatus");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("paymenttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PaymentTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("paymenttermscode");
			set
			{
				this.OnPropertyChanging("PaymentTermsCode");
					this.SetAttributeValue("paymenttermscode", value);
				this.OnPropertyChanged("PaymentTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredappointmentdaycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredAppointmentDayCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredappointmentdaycode");
			set
			{
				this.OnPropertyChanging("PreferredAppointmentDayCode");
					this.SetAttributeValue("preferredappointmentdaycode", value);
				this.OnPropertyChanged("PreferredAppointmentDayCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredappointmenttimecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredAppointmentTimeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredappointmenttimecode");
			set
			{
				this.OnPropertyChanging("PreferredAppointmentTimeCode");
					this.SetAttributeValue("preferredappointmenttimecode", value);
				this.OnPropertyChanged("PreferredAppointmentTimeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredcontactmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredContactMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredcontactmethodcode");
			set
			{
				this.OnPropertyChanging("PreferredContactMethodCode");
					this.SetAttributeValue("preferredcontactmethodcode", value);
				this.OnPropertyChanged("PreferredContactMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shippingmethodcode");
			set
			{
				this.OnPropertyChanging("ShippingMethodCode");
					this.SetAttributeValue("shippingmethodcode", value);
				this.OnPropertyChanged("ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("territorycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue TerritoryCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("territorycode");
			set
			{
				this.OnPropertyChanging("TerritoryCode");
					this.SetAttributeValue("territorycode", value);
				this.OnPropertyChanged("TerritoryCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public ContactState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((ContactState)(System.Enum.ToObject(typeof(ContactState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum InvoiceState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed__deprecated_ = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Paid = 2,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 3,
	}
	public partial class Invoice
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("paymenttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PaymentTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("paymenttermscode");
			set
			{
				this.OnPropertyChanging("PaymentTermsCode");
					this.SetAttributeValue("paymenttermscode", value);
				this.OnPropertyChanged("PaymentTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("pricingerrorcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PricingErrorCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("pricingerrorcode");
			set
			{
				this.OnPropertyChanging("PricingErrorCode");
					this.SetAttributeValue("pricingerrorcode", value);
				this.OnPropertyChanged("PricingErrorCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("prioritycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PriorityCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
			set
			{
				this.OnPropertyChanging("PriorityCode");
					this.SetAttributeValue("prioritycode", value);
				this.OnPropertyChanged("PriorityCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shippingmethodcode");
			set
			{
				this.OnPropertyChanging("ShippingMethodCode");
					this.SetAttributeValue("shippingmethodcode", value);
				this.OnPropertyChanged("ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shipto_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShipTo_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shipto_freighttermscode");
			set
			{
				this.OnPropertyChanging("ShipTo_FreightTermsCode");
					this.SetAttributeValue("shipto_freighttermscode", value);
				this.OnPropertyChanged("ShipTo_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("skippricecalculation")]
		public Microsoft.Xrm.Sdk.OptionSetValue SkipPriceCalculation
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("skippricecalculation");
			set
			{
				this.OnPropertyChanging("SkipPriceCalculation");
					this.SetAttributeValue("skippricecalculation", value);
				this.OnPropertyChanged("SkipPriceCalculation");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public InvoiceState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((InvoiceState)(System.Enum.ToObject(typeof(InvoiceState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum LeadState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Qualified = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disqualified = 2,
	}
	public partial class Lead
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address1_AddressTypeCode");
					this.SetAttributeValue("address1_addresstypecode", value);
				this.OnPropertyChanged("Address1_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address1_ShippingMethodCode");
					this.SetAttributeValue("address1_shippingmethodcode", value);
				this.OnPropertyChanged("Address1_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address2_AddressTypeCode");
					this.SetAttributeValue("address2_addresstypecode", value);
				this.OnPropertyChanged("Address2_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address2_ShippingMethodCode");
					this.SetAttributeValue("address2_shippingmethodcode", value);
				this.OnPropertyChanged("Address2_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("budgetstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue BudgetStatus
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("budgetstatus");
			set
			{
				this.OnPropertyChanging("BudgetStatus");
					this.SetAttributeValue("budgetstatus", value);
				this.OnPropertyChanged("BudgetStatus");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("industrycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue IndustryCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("industrycode");
			set
			{
				this.OnPropertyChanging("IndustryCode");
					this.SetAttributeValue("industrycode", value);
				this.OnPropertyChanged("IndustryCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("initialcommunication")]
		public Microsoft.Xrm.Sdk.OptionSetValue InitialCommunication
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("initialcommunication");
			set
			{
				this.OnPropertyChanging("InitialCommunication");
					this.SetAttributeValue("initialcommunication", value);
				this.OnPropertyChanged("InitialCommunication");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("leadqualitycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue LeadQualityCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("leadqualitycode");
			set
			{
				this.OnPropertyChanging("LeadQualityCode");
					this.SetAttributeValue("leadqualitycode", value);
				this.OnPropertyChanged("LeadQualityCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("leadsourcecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue LeadSourceCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("leadsourcecode");
			set
			{
				this.OnPropertyChanging("LeadSourceCode");
					this.SetAttributeValue("leadsourcecode", value);
				this.OnPropertyChanged("LeadSourceCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("need")]
		public Microsoft.Xrm.Sdk.OptionSetValue Need
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("need");
			set
			{
				this.OnPropertyChanging("Need");
					this.SetAttributeValue("need", value);
				this.OnPropertyChanged("Need");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredcontactmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredContactMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredcontactmethodcode");
			set
			{
				this.OnPropertyChanging("PreferredContactMethodCode");
					this.SetAttributeValue("preferredcontactmethodcode", value);
				this.OnPropertyChanged("PreferredContactMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("prioritycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PriorityCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
			set
			{
				this.OnPropertyChanging("PriorityCode");
					this.SetAttributeValue("prioritycode", value);
				this.OnPropertyChanged("PriorityCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("purchaseprocess")]
		public Microsoft.Xrm.Sdk.OptionSetValue PurchaseProcess
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("purchaseprocess");
			set
			{
				this.OnPropertyChanging("PurchaseProcess");
					this.SetAttributeValue("purchaseprocess", value);
				this.OnPropertyChanged("PurchaseProcess");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("purchasetimeframe")]
		public Microsoft.Xrm.Sdk.OptionSetValue PurchaseTimeFrame
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("purchasetimeframe");
			set
			{
				this.OnPropertyChanging("PurchaseTimeFrame");
					this.SetAttributeValue("purchasetimeframe", value);
				this.OnPropertyChanged("PurchaseTimeFrame");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("salesstage")]
		public Microsoft.Xrm.Sdk.OptionSetValue SalesStage
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("salesstage");
			set
			{
				this.OnPropertyChanging("SalesStage");
					this.SetAttributeValue("salesstage", value);
				this.OnPropertyChanged("SalesStage");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("salesstagecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue SalesStageCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("salesstagecode");
			set
			{
				this.OnPropertyChanging("SalesStageCode");
					this.SetAttributeValue("salesstagecode", value);
				this.OnPropertyChanged("SalesStageCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public LeadState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((LeadState)(System.Enum.ToObject(typeof(LeadState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum OpportunityState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Open = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Won = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lost = 2,
	}
	public partial class Opportunity
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("budgetstatus")]
		public BudgetEnum? Budgetstatus
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("budgetstatus");
				if (optionSet != null)
				{
					return (BudgetEnum)optionSet.Value;
				}
				return null;
			}
			set
			{
				this.OnPropertyChanging("Budgetstatus");
				if (value != null)
				{
					this.SetAttributeValue("budgetstatus", new Microsoft.Xrm.Sdk.OptionSetValue((int)value.Value));
					this.OnPropertyChanged("Budgetstatus");
					return;
				}
				this.SetAttributeValue("budgetstatus", null);
				this.OnPropertyChanged("Budgetstatus");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("initialcommunication")]
		public Microsoft.Xrm.Sdk.OptionSetValue InitialCommunication
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("initialcommunication");
			set
			{
				this.OnPropertyChanging("InitialCommunication");
					this.SetAttributeValue("initialcommunication", value);
				this.OnPropertyChanged("InitialCommunication");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("need")]
		public Microsoft.Xrm.Sdk.OptionSetValue Need
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("need");
			set
			{
				this.OnPropertyChanging("Need");
					this.SetAttributeValue("need", value);
				this.OnPropertyChanged("Need");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("opportunityratingcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue OpportunityRatingCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("opportunityratingcode");
			set
			{
				this.OnPropertyChanging("OpportunityRatingCode");
					this.SetAttributeValue("opportunityratingcode", value);
				this.OnPropertyChanged("OpportunityRatingCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("pricingerrorcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PricingErrorCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("pricingerrorcode");
			set
			{
				this.OnPropertyChanging("PricingErrorCode");
					this.SetAttributeValue("pricingerrorcode", value);
				this.OnPropertyChanged("PricingErrorCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("prioritycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PriorityCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
			set
			{
				this.OnPropertyChanging("PriorityCode");
					this.SetAttributeValue("prioritycode", value);
				this.OnPropertyChanged("PriorityCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("purchaseprocess")]
		public Microsoft.Xrm.Sdk.OptionSetValue PurchaseProcess
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("purchaseprocess");
			set
			{
				this.OnPropertyChanging("PurchaseProcess");
					this.SetAttributeValue("purchaseprocess", value);
				this.OnPropertyChanged("PurchaseProcess");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("purchasetimeframe")]
		public Microsoft.Xrm.Sdk.OptionSetValue PurchaseTimeframe
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("purchasetimeframe");
			set
			{
				this.OnPropertyChanging("PurchaseTimeframe");
					this.SetAttributeValue("purchasetimeframe", value);
				this.OnPropertyChanged("PurchaseTimeframe");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("salesstage")]
		public Microsoft.Xrm.Sdk.OptionSetValue SalesStage
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("salesstage");
			set
			{
				this.OnPropertyChanging("SalesStage");
					this.SetAttributeValue("salesstage", value);
				this.OnPropertyChanged("SalesStage");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("salesstagecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue SalesStageCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("salesstagecode");
			set
			{
				this.OnPropertyChanging("SalesStageCode");
					this.SetAttributeValue("salesstagecode", value);
				this.OnPropertyChanged("SalesStageCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("skippricecalculation")]
		public Microsoft.Xrm.Sdk.OptionSetValue SkipPriceCalculation
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("skippricecalculation");
			set
			{
				this.OnPropertyChanging("SkipPriceCalculation");
					this.SetAttributeValue("skippricecalculation", value);
				this.OnPropertyChanged("SkipPriceCalculation");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("timeline")]
		public Microsoft.Xrm.Sdk.OptionSetValue TimeLine
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("timeline");
			set
			{
				this.OnPropertyChanging("TimeLine");
					this.SetAttributeValue("timeline", value);
				this.OnPropertyChanged("TimeLine");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public OpportunityState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((OpportunityState)(System.Enum.ToObject(typeof(OpportunityState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum SalesOrderState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Submitted = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Canceled = 2,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fulfilled = 3,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoiced = 4,
	}
	public partial class SalesOrder
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("freighttermscode");
			set
			{
				this.OnPropertyChanging("FreightTermsCode");
					this.SetAttributeValue("freighttermscode", value);
				this.OnPropertyChanged("FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("paymenttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PaymentTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("paymenttermscode");
			set
			{
				this.OnPropertyChanging("PaymentTermsCode");
					this.SetAttributeValue("paymenttermscode", value);
				this.OnPropertyChanged("PaymentTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("pricingerrorcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PricingErrorCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("pricingerrorcode");
			set
			{
				this.OnPropertyChanging("PricingErrorCode");
					this.SetAttributeValue("pricingerrorcode", value);
				this.OnPropertyChanged("PricingErrorCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("prioritycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PriorityCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
			set
			{
				this.OnPropertyChanging("PriorityCode");
					this.SetAttributeValue("prioritycode", value);
				this.OnPropertyChanged("PriorityCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shippingmethodcode");
			set
			{
				this.OnPropertyChanging("ShippingMethodCode");
					this.SetAttributeValue("shippingmethodcode", value);
				this.OnPropertyChanged("ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shipto_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShipTo_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shipto_freighttermscode");
			set
			{
				this.OnPropertyChanging("ShipTo_FreightTermsCode");
					this.SetAttributeValue("shipto_freighttermscode", value);
				this.OnPropertyChanged("ShipTo_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("skippricecalculation")]
		public Microsoft.Xrm.Sdk.OptionSetValue SkipPriceCalculation
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("skippricecalculation");
			set
			{
				this.OnPropertyChanging("SkipPriceCalculation");
					this.SetAttributeValue("skippricecalculation", value);
				this.OnPropertyChanged("SkipPriceCalculation");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public SalesOrderState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((SalesOrderState)(System.Enum.ToObject(typeof(SalesOrderState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum QuoteState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Won = 2,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 3,
	}
	public partial class Quote
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("freighttermscode");
			set
			{
				this.OnPropertyChanging("FreightTermsCode");
					this.SetAttributeValue("freighttermscode", value);
				this.OnPropertyChanged("FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("paymenttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PaymentTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("paymenttermscode");
			set
			{
				this.OnPropertyChanging("PaymentTermsCode");
					this.SetAttributeValue("paymenttermscode", value);
				this.OnPropertyChanged("PaymentTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("pricingerrorcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PricingErrorCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("pricingerrorcode");
			set
			{
				this.OnPropertyChanging("PricingErrorCode");
					this.SetAttributeValue("pricingerrorcode", value);
				this.OnPropertyChanged("PricingErrorCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shippingmethodcode");
			set
			{
				this.OnPropertyChanging("ShippingMethodCode");
					this.SetAttributeValue("shippingmethodcode", value);
				this.OnPropertyChanged("ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("shipto_freighttermscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ShipTo_FreightTermsCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("shipto_freighttermscode");
			set
			{
				this.OnPropertyChanging("ShipTo_FreightTermsCode");
					this.SetAttributeValue("shipto_freighttermscode", value);
				this.OnPropertyChanged("ShipTo_FreightTermsCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("skippricecalculation")]
		public Microsoft.Xrm.Sdk.OptionSetValue SkipPriceCalculation
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("skippricecalculation");
			set
			{
				this.OnPropertyChanging("SkipPriceCalculation");
					this.SetAttributeValue("skippricecalculation", value);
				this.OnPropertyChanged("SkipPriceCalculation");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("StatusCode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public QuoteState? StateCode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((QuoteState)(System.Enum.ToObject(typeof(QuoteState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
	}
	public partial class SystemUser
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("accessmode")]
		public Microsoft.Xrm.Sdk.OptionSetValue AccessMode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("accessmode");
			set
			{
				this.OnPropertyChanging("AccessMode");
					this.SetAttributeValue("accessmode", value);
				this.OnPropertyChanged("AccessMode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address1_AddressTypeCode");
					this.SetAttributeValue("address1_addresstypecode", value);
				this.OnPropertyChanged("Address1_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address1_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address1_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address1_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address1_ShippingMethodCode");
					this.SetAttributeValue("address1_shippingmethodcode", value);
				this.OnPropertyChanged("Address1_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_addresstypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_AddressTypeCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_addresstypecode");
			set
			{
				this.OnPropertyChanging("Address2_AddressTypeCode");
					this.SetAttributeValue("address2_addresstypecode", value);
				this.OnPropertyChanged("Address2_AddressTypeCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("address2_shippingmethodcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue Address2_ShippingMethodCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("address2_shippingmethodcode");
			set
			{
				this.OnPropertyChanging("Address2_ShippingMethodCode");
					this.SetAttributeValue("address2_shippingmethodcode", value);
				this.OnPropertyChanged("Address2_ShippingMethodCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("caltype")]
		public Microsoft.Xrm.Sdk.OptionSetValue CALType
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("caltype");
			set
			{
				this.OnPropertyChanging("CALType");
					this.SetAttributeValue("caltype", value);
				this.OnPropertyChanged("CALType");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("emailrouteraccessapproval")]
		public Microsoft.Xrm.Sdk.OptionSetValue EmailRouterAccessApproval
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("emailrouteraccessapproval");
			set
			{
				this.OnPropertyChanging("EmailRouterAccessApproval");
					this.SetAttributeValue("emailrouteraccessapproval", value);
				this.OnPropertyChanged("EmailRouterAccessApproval");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("incomingemaildeliverymethod")]
		public Microsoft.Xrm.Sdk.OptionSetValue IncomingEmailDeliveryMethod
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("incomingemaildeliverymethod");
			set
			{
				this.OnPropertyChanging("IncomingEmailDeliveryMethod");
					this.SetAttributeValue("incomingemaildeliverymethod", value);
				this.OnPropertyChanged("IncomingEmailDeliveryMethod");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("invitestatuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue InviteStatusCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("invitestatuscode");
			set
			{
				this.OnPropertyChanging("InviteStatusCode");
					this.SetAttributeValue("invitestatuscode", value);
				this.OnPropertyChanged("InviteStatusCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("outgoingemaildeliverymethod")]
		public Microsoft.Xrm.Sdk.OptionSetValue OutgoingEmailDeliveryMethod
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("outgoingemaildeliverymethod");
			set
			{
				this.OnPropertyChanging("OutgoingEmailDeliveryMethod");
					this.SetAttributeValue("outgoingemaildeliverymethod", value);
				this.OnPropertyChanged("OutgoingEmailDeliveryMethod");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredaddresscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredAddressCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredaddresscode");
			set
			{
				this.OnPropertyChanging("PreferredAddressCode");
					this.SetAttributeValue("preferredaddresscode", value);
				this.OnPropertyChanged("PreferredAddressCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredemailcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredEmailCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredemailcode");
			set
			{
				this.OnPropertyChanging("PreferredEmailCode");
					this.SetAttributeValue("preferredemailcode", value);
				this.OnPropertyChanged("PreferredEmailCode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalName("preferredphonecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PreferredPhoneCode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("preferredphonecode");
			set
			{
				this.OnPropertyChanging("PreferredPhoneCode");
					this.SetAttributeValue("preferredphonecode", value);
				this.OnPropertyChanged("PreferredPhoneCode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum kipon_datepocState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	public partial class kipon_datepoc
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue statuscode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("statuscode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("statuscode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public kipon_datepocState? statecode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((kipon_datepocState)(System.Enum.ToObject(typeof(kipon_datepocState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("statecode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("statecode");
			}
		}
	}
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Kipon.Solid.Plugin", "1.0.9.4")]
	public enum kipon_multitestState
	{
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	public partial class kipon_multitest
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue statuscode
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			set
			{
				this.OnPropertyChanging("statuscode");
					this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("statuscode");
			}
		}
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public kipon_multitestState? statecode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((kipon_multitestState)(System.Enum.ToObject(typeof(kipon_multitestState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("statecode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("statecode");
			}
		}
	}
	public partial class Template
	{
		[Microsoft.Xrm.Sdk.AttributeLogicalName("componentstate")]
		public Microsoft.Xrm.Sdk.OptionSetValue ComponentState
		{
			get => this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("componentstate");
			set
			{
				this.OnPropertyChanging("ComponentState");
					this.SetAttributeValue("componentstate", value);
				this.OnPropertyChanged("ComponentState");
			}
		}
	}
}

#warning change generated namespace
namespace Kipon.Online.Plugin.Framework.Implementations
{
	public class DefaultStaticInitializer : Kipon.Xrm.ServiceAPI.IStaticInitializer
	{
		void Kipon.Xrm.ServiceAPI.IStaticInitializer.Initialize()
		{
#warning add to code generate
			var entittypes = Kipon.Xrm.Extensions.Sdk.KiponSdkGeneratedExtensionMethods.entittypes;
			var entityLogicalNameToTypeCodeIndex = Kipon.Xrm.Extensions.Sdk.KiponSdkGeneratedExtensionMethods.entityLogicalNameToTypeCodeIndex;
			var typecodeToEntityLogicalNameIndex = Kipon.Xrm.Extensions.Sdk.KiponSdkGeneratedExtensionMethods.typecodeToEntityLogicalNameIndex;

			entittypes[Kipon.Solid.Plugin.Entities.Account.EntityLogicalName] = typeof(Kipon.Solid.Plugin.Entities.Account);
			entityLogicalNameToTypeCodeIndex["entitydataprovider"] = 78;

			Kipon.Xrm.Services.NamingService.Add("entitydataprovider", "entitydataproviderid", "name");
		}

    }
}
namespace Kipon.Solid.Plugin.Actions
{
	[Kipon.Xrm.Attributes.LogicalName("account")]
	public partial interface IAccountCountContactsRequest: Kipon.Xrm.ActionTarget<Kipon.Solid.Plugin.Entities.Account>
	{
		string Name { get; }
	}
	public partial class AccountCountContactsResponse
	{
		[Kipon.Xrm.Attributes.Output("AMoney", true)]
		 public Microsoft.Xrm.Sdk.Money AMoney { get; set; }
		[Kipon.Xrm.Attributes.Output("Count", true)]
		 public int Count { get; set; }
	}
	public partial interface IAnunboundedactionRequest
	{
		string Name { get; }
		string Document { get; }
		Microsoft.Xrm.Sdk.OptionSetValue Picklist { get; }
	}
	public partial class AnunboundedactionResponse
	{
		[Kipon.Xrm.Attributes.Output("Id", true)]
		 public string Id { get; set; }
	}
	[Kipon.Xrm.Attributes.LogicalName("lead")]
	public partial interface IQualityLeadRequest: Kipon.Xrm.ActionTarget<Kipon.Solid.Plugin.Entities.Lead>
	{
		Microsoft.Xrm.Sdk.EntityReference OpportunityCurrencyId { get; }
		bool CreateContact { get; }
		Microsoft.Xrm.Sdk.OptionSetValue Status { get; }
		bool? SuppressDuplicateDetection { get; }
		Microsoft.Xrm.Sdk.EntityReference ProcessInstanceId { get; }
		bool CreateOpportunity { get; }
		bool CreateAccount { get; }
		Microsoft.Xrm.Sdk.EntityReference SourceCampaignId { get; }
		Microsoft.Xrm.Sdk.EntityReference OpportunityCustomerId { get; }
	}
	public partial class QualityLeadResponse
	{
		[Kipon.Xrm.Attributes.Output("CreatedEntities", true)]
		 public Microsoft.Xrm.Sdk.EntityReferenceCollection CreatedEntities { get; set; }
	}
}
namespace Kipon.Solid.Plugin.Actions.Implement
{
	using Kipon.Solid.Plugin.Actions;
	using Kipon.Xrm.Actions;
	public partial class AccountCountContactsRequest : AbstractActionRequest, IAccountCountContactsRequest
	{
		public AccountCountContactsRequest(Microsoft.Xrm.Sdk.IPluginExecutionContext ctx): base(ctx){ }
		public string Name {get => this.ValueOf<string>("Name");}
		public Microsoft.Xrm.Sdk.EntityReference Target {get => this.ValueOf<Microsoft.Xrm.Sdk.EntityReference>("Target");}
	}
	public partial class AnunboundedactionRequest : AbstractActionRequest, IAnunboundedactionRequest
	{
		public AnunboundedactionRequest(Microsoft.Xrm.Sdk.IPluginExecutionContext ctx): base(ctx){ }
		public string Name {get => this.ValueOf<string>("Name");}
		public string Document {get => this.ValueOf<string>("Document");}
		public Microsoft.Xrm.Sdk.OptionSetValue Picklist {get => this.ValueOf<Microsoft.Xrm.Sdk.OptionSetValue>("Picklist");}
	}
	public partial class QualityLeadRequest : AbstractActionRequest, IQualityLeadRequest
	{
		public QualityLeadRequest(Microsoft.Xrm.Sdk.IPluginExecutionContext ctx): base(ctx){ }
		public Microsoft.Xrm.Sdk.EntityReference OpportunityCurrencyId {get => this.ValueOf<Microsoft.Xrm.Sdk.EntityReference>("OpportunityCurrencyId");}
		public bool CreateContact {get => this.ValueOf<bool>("CreateContact");}
		public Microsoft.Xrm.Sdk.EntityReference Target {get => this.ValueOf<Microsoft.Xrm.Sdk.EntityReference>("Target");}
		public Microsoft.Xrm.Sdk.OptionSetValue Status {get => this.ValueOf<Microsoft.Xrm.Sdk.OptionSetValue>("Status");}
		public bool? SuppressDuplicateDetection {get => this.ValueOf<bool?>("SuppressDuplicateDetection");}
		public Microsoft.Xrm.Sdk.EntityReference ProcessInstanceId {get => this.ValueOf<Microsoft.Xrm.Sdk.EntityReference>("ProcessInstanceId");}
		public bool CreateOpportunity {get => this.ValueOf<bool>("CreateOpportunity");}
		public bool CreateAccount {get => this.ValueOf<bool>("CreateAccount");}
		public Microsoft.Xrm.Sdk.EntityReference SourceCampaignId {get => this.ValueOf<Microsoft.Xrm.Sdk.EntityReference>("SourceCampaignId");}
		public Microsoft.Xrm.Sdk.EntityReference OpportunityCustomerId {get => this.ValueOf<Microsoft.Xrm.Sdk.EntityReference>("OpportunityCustomerId");}
	}
}
