// Dynamics 365 svcutil extension tool by Kipon ApS, Kjeld Poulsen
// This file is autogenerated. Do not touch the code manually

namespace Kipon.Dynamics.Plugin.Entities
{
	public partial interface IUnitOfWork
	{
		#region entity repositories
		IRepository<Account> Accounts { get; }
		IRepository<Contact> Contacts { get; }
		IRepository<Opportunity> Opportunities { get; }
		IRepository<SalesOrder> Salesorders { get; }
		IRepository<Quote> Quotes { get; }
		#endregion
	}
}
